version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: growth-compass-db
    environment:
      POSTGRES_DB: growth_compass
      POSTGRES_USER: growth_user
      POSTGRES_PASSWORD: growth_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: growth-compass-adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: