#!/bin/bash

echo "Quick deployment fix for Growth Compass on VPS"
echo "=============================================="
echo ""
echo "Copy and paste these commands one by one after SSHing into the server:"
echo ""
echo "ssh root@62.171.175.130"
echo "# Password: 63r4k5PS"
echo ""
echo "# 1. First, check what's in the apps folder:"
echo "ls -la /root/apps/"
echo ""
echo "# 2. Kill any process on port 9001:"
echo "fuser -k 9001/tcp"
echo "lsof -ti:9001 | xargs kill -9"
echo ""
echo "# 3. Open firewall port 9001 (CRITICAL!):"
echo "ufw allow 9001/tcp"
echo "ufw allow 9001"
echo "iptables -A INPUT -p tcp --dport 9001 -j ACCEPT"
echo "iptables -A OUTPUT -p tcp --sport 9001 -j ACCEPT"
echo ""
echo "# 4. Navigate to apps folder and clone:"
echo "cd /root/apps"
echo "git clone https://github.com/srijan816/growth.git growth-compass"
echo "cd growth-compass"
echo ""
echo "# 5. Install dependencies:"
echo "npm install"
echo ""
echo "# 6. Create .env file:"
echo "cat > .env << 'EOF'"
echo "DATABASE_URL=postgresql://growthcompass:secure_password_123@localhost:5432/growth_compass"
echo "NEXTAUTH_URL=http://62.171.175.130:9001"
echo "NEXTAUTH_SECRET=your-secret-key-here-minimum-32-characters-long"
echo "NODE_ENV=production"
echo "PORT=9001"
echo "HOST=0.0.0.0"
echo "EOF"
echo ""
echo "# 7. Build the application:"
echo "npm run build"
echo ""
echo "# 8. Start directly with Node (for testing):"
echo "PORT=9001 HOST=0.0.0.0 npm start &"
echo ""
echo "# OR start with PM2:"
echo "pm2 stop all"
echo "pm2 delete all"
echo ""
echo "cat > ecosystem.config.js << 'EOF'"
echo "module.exports = {"
echo "  apps: [{"
echo "    name: 'growth-compass',"
echo "    script: 'npm',"
echo "    args: 'start',"
echo "    cwd: '/root/apps/growth-compass',"
echo "    env: {"
echo "      NODE_ENV: 'production',"
echo "      PORT: 9001,"
echo "      HOST: '0.0.0.0'"
echo "    }"
echo "  }]"
echo "};"
echo "EOF"
echo ""
echo "pm2 start ecosystem.config.js"
echo "pm2 save"
echo ""
echo "# 9. Check if it's running:"
echo "pm2 status"
echo "netstat -tlnp | grep 9001"
echo "curl http://localhost:9001"
echo ""
echo "# 10. If still not working, check logs:"
echo "pm2 logs growth-compass --lines 50"
echo ""